import '@/app/ui/global.css';

import { inter } from '@/app/ui/fonts';
import { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: {
    template: '%s | Acme Dashboard',
    default: 'Acme Dashboard',
  },
  description: 'Generated by create next app',
  creator: 'Emrah Atalay',
};

export default function RootLayout({
  children,
  createInvoiceModal,
}: {
  children: ReactNode;
  createInvoiceModal?: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {createInvoiceModal}
        {children}
      </body>
    </html>
  );
}
